### PR TITLE
Node 6.5.0

### PR DESCRIPTION
**Pull request by huseyinkozan**
Node 6.5.0 patchs. Only `--without-intl` and some trials to enable intl.

Signed the Tessel CLA.

### CODE REVIEW

**Comment by huseyinkozan** [comment]
Relevant issues:
https://github.com/tessel/t2-firmware/issues/206#issuecomment-246131345
https://github.com/nodejs/node/issues/7173#issuecomment-246129759

Patch coming from (patch merged after 6.5.0) :
https://github.com/nodejs/node/issues/8233

**Comment by rwaldron** [comment]
@huseyinkozan can you update this to 6.9.0—thanks!!

**Comment by huseyinkozan** [comment]
@rwaldron Tried to update but no luck at first build. No time to retry.
Here the trial codes: https://github.com/huseyinkozan/openwrt-tessel/tree/node-6.9.0

**Comment by johnnyman727** [comment]
I've updated @huseyinkozan's branch to Node `6.9.2` but I was also unable to compile properly. Here is the error that gets returned:
```
/home/openwrt-tessel/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/node-v6.9.2/out/Release/obj/gen/blink/platform/inspector_protocol/InspectorProtocol.cpp: In function 'void blink::protocol::internal::intToStr(int, char*, size_t)':
/home/openwrt-tessel/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/node-v6.9.2/out/Release/obj/gen/blink/platform/inspector_protocol/InspectorProtocol.cpp:23:5: error: 'snprintf' is not a member of 'std'
     std::snprintf(buffer, length, "%d", number);
     ^
/home/openwrt-tessel/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/node-v6.9.2/out/Release/obj/gen/blink/platform/inspector_protocol/InspectorProtocol.cpp: In function 'void blink::protocol::internal::doubleToStr(double, char*, size_t)':
/home/openwrt-tessel/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/node-v6.9.2/out/Release/obj/gen/blink/platform/inspector_protocol/InspectorProtocol.cpp:28:5: error: 'snprintf' is not a member of 'std'
     std::snprintf(buffer, length, "%f", number);
     ^
/home/openwrt-tessel/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/node-v6.9.2/out/Release/obj/gen/blink/platform/inspector_protocol/InspectorProtocol.cpp: In function 'void blink::protocol::internal::doubleToStr3(double, char*, size_t)':
/home/openwrt-tessel/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/node-v6.9.2/out/Release/obj/gen/blink/platform/inspector_protocol/InspectorProtocol.cpp:33:5: error: 'snprintf' is not a member of 'std'
     std::snprintf(buffer, length, "%.3g", number);
     ^
/home/openwrt-tessel/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/node-v6.9.2/out/Release/obj/gen/blink/platform/inspector_protocol/InspectorProtocol.cpp: In function 'void blink::protocol::internal::doubleToStr6(double, char*, size_t)':
/home/openwrt-tessel/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/node-v6.9.2/out/Release/obj/gen/blink/platform/inspector_protocol/InspectorProtocol.cpp:38:5: error: 'snprintf' is not a member of 'std'
     std::snprintf(buffer, length, "%.6g", number);
```

I haven't had time to look into this much but does anyone have an instinct as to what might be the issue? Incorrect C++ compiler?

**Comment by johnnyman727** [comment]
I think [this commented out line](https://github.com/huseyinkozan/openwrt-tessel/blob/5c178a5f567ed6f7e2afb047e4fc850b10a81ec8/package/node/node/Makefile#L21) might be the issue. Trying to compile again...

**Comment by johnnyman727** [comment]
Nope, the issue still occurs 😭

**Comment by johnnyman727** [comment]
@thealphanerd, @rwaldron mentioned that you might have some insight here. Do you have any ideas why we'd be getting C++ compilation errors when trying to compile Node (on MIPS)?

**Comment by TheAlphaNerd** [comment]
was 6.9.1 working? 

is this using the default tarball? the failing bits seem related to inspector, which there were some updates to in the release. /cc @nodejs/v8

**Comment by rwaldron** [comment]
> was 6.9.1 working?

No, we're only just now getting a chance to work on the upgrade to Node 6.x. The patch we received for 6.5.0 compiles correctly, but @johnnyman727 was hoping to build 6.9.2.

**Comment by TheAlphaNerd** [comment]
I think y'all need a newer version of gcc. snprintf is a c++ 11 feature.
which version of gcc are you using?

**Comment by johnnyman727** [comment]
We're running with gcc 4.8.4 on our build box currently. Do you think we need v6+?

**Comment by TheAlphaNerd** [comment]
it should be working with gcc 4.8.x

can you try adding `-std=c++11` as a compile flag?
/cc @bnoordhuis

**Comment by bnoordhuis** [comment]
It's probably a compatibility issue with the C++ standard library headers that you are compiling against because the compiler itself must be C++11-compatible if you can get to the point where InspectorProtocol.cpp is generated and compiled.

If you can live without V8 inspector (DevTools) support, do `./configure --without-inspector`, otherwise do `s/std::snprintf/snprintf/` to the files in deps/v8_inspector.  We may be able to land that change upstream as well.

**Comment by huseyinkozan** [comment]
Hi all,

I tried to compile but no luck. Here the results :
Adding these lines to `packages/no/no/Makefile` didnt solve:
```
TARGET_CFLAGS += -std=c++11
TARGET_CPPFLAGS += -std=c++11
TARGET_CXXFLAGS += -std=c++11
```

Then I found this : http://src.mouf.net/ports/view/head/www/node/Makefile?rev=422711
And tried adding this line to `package/node/node/Makefile`:
```
TARGET_CXXFLAGS += -D_GLIBCXX_USE_C99
```
And passed the `std::snprintf` error.

But we have another issue because of old uclibc (I thing). Like : 
* https://github.com/nodejs/node/issues/7316
* https://github.com/nodejs/node/issues/3896

We can try this mentioned patch : https://git.busybox.net/uClibc/commit/?id=6c4538905e65ceb203f59aaa9a61728e81c6bc0a

Or, update a newer version. It will be so good if we update/upgrade all OpenWRT.

Thats all for today, see you

**Comment by rwaldron** [comment]
> If you can live without V8 inspector (DevTools) support, do ./configure --without-inspector, 


I wonder if this would result in an observable size reduction?

**Comment by huseyinkozan** [comment]
@rwaldron Trying ...

**Comment by huseyinkozan** [comment]
Still same
```
/home/huseyinkozan/openwrt-tessel/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/node-v6.9.4/out/Release/obj.target/v8_base/deps/v8/src/assembler.o: In function `v8::internal::wasm::f32_nearest_int_wrapper(float*)':
assembler.cc:(.text._ZN2v88internal4wasmL23f32_nearest_int_wrapperEPf+0x18): undefined reference to `nearbyintf'
collect2: error: ld returned 1 exit status
make[5]: *** [/home/huseyinkozan/openwrt-tessel/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/node-v6.9.4/out/Release/node] Error 1
make[5]: Leaving directory `/home/huseyinkozan/openwrt-tessel/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/node-v6.9.4/out'
make[4]: *** [node] Error 2
make[4]: Leaving directory `/home/huseyinkozan/openwrt-tessel/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/node-v6.9.4'
make[3]: *** [/home/huseyinkozan/openwrt-tessel/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/node-v6.9.4/.built] Error 2
make[3]: Leaving directory `/home/huseyinkozan/openwrt-tessel/package/node/node'
make[2]: *** [package/feeds/tessel/node/compile] Error 2
make[2]: Leaving directory `/home/huseyinkozan/openwrt-tessel/openwrt'
make[1]: *** [/home/huseyinkozan/openwrt-tessel/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/huseyinkozan/openwrt-tessel/openwrt'
make: *** [world] Error 2
huseyinkozan@tessel-builder:~/openwrt-tessel/openwrt$ 

```

**Comment by bnoordhuis** [comment]
Untested, but you might be able to get away with `s/nearbyintf/roundf/`.  Please run the test suite afterwards, though. :-)

**Comment by rwaldron** [comment]
@huseyinkozan you're a champ for that follow up ❤️

**Comment by rwaldron** [comment]
@bnoordhuis interesting, definitely worth a try

**Comment by huseyinkozan** [comment]
https://github.com/artynet/openwrt-git/tree/openwrt-1505-setup-03/package/linino
Note : attention to the node packages!

Can we combine/use that OpenWRT tree ?

**Comment by rwaldron** [comment]
After much consideration, I think we should upgrade to Node 6.5.0 per @huseyinkozan original patch. We can work on newer 6.x.x upgrades after that.

**Comment by HipsterBrown** [comment]
@rwaldron Agreed. 👍

**Comment by rwaldron** [comment]
I'm going to work on resolving the existing conflict and get this landed today.

**Comment by MylesBorins** [comment]
Lmk if I can help at all

**Comment by rwaldron** [comment]
@huseyinkozan I've landed this in master

**Comment by rwaldron** [comment]
Temporarily reverted

**Comment by huseyinkozan** [comment]
Hi,

I will get my Tessel few days later. I may look at again, If I have time.

**Comment by MylesBorins** [comment]
I'm open to floating a patch on node for this header.

**Comment by rwaldron** [comment]
@huseyinkozan thanks, I'm in the process of getting chaos calmer upgraded as well. 


@MylesBorins I appreciate the offer, but I still haven't made a successful build with any patches or headers :| (Fact: that is likely because I don't know what the hell I'm doing)

**Comment by huseyinkozan** [comment]
@rwaldron I see. I tried to build with these sub modules:
* openwrt : 2017-04-26
* upstream-pacakges : for-15.05

I got `nearbyint` error agin. Then made some digg about uClibc, which was dead at 2012. I am looking to switch the toolchain to `musl`, now.

**Comment by rwaldron** [comment]
@huseyinkozan is this relevant: https://github.com/tessel/openwrt/pull/2/files ?

**Comment by huseyinkozan** [comment]
@rwaldron I am not sure to use a not maintained lib. Also, there is a comparison:
http://www.etalabs.net/compare_libcs.html

I want to try to build. Nothing to loose, rather than time : - /

**Comment by huseyinkozan** [comment]
@rwaldron Added the patch you noted, but same error. Cannot find how to switch to musl.

**Comment by kevinmehall** [comment]
I'd recommend rebasing on LEDE 17.01 which switched to musl by default. It's possible to switch 15.05 to musl in the build configuration, but not well tested AFAIK.

**Comment by rwaldron** [comment]
@kevinmehall just so I understand correctly, you're suggesting that we try to apply our existing openwrt patches to the `lede-17.01` tag (from https://github.com/lede-project/source)? It's doable, but there's a merge conflict on the first patch: https://github.com/tessel/openwrt/commit/4e1c826ed37dcdf577adcb8a6fe257c940115119 

```
$ gst
On branch lede-17.01-rebase
You are currently cherry-picking commit 4e1c826ed3.
  (fix conflicts and run "git cherry-pick --continue")
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

Changes to be committed:

	new file:   target/linux/ramips/patches-3.14/999-mt7620-spi-cs1.patch
	new file:   target/linux/ramips/patches-3.18/999-mt7620-spi-cs1.patch

Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both modified:   target/linux/ramips/dts/mt7620n.dtsi
```

It appears minor, but I don't know how to resolve this: 

```dtsi
<<<<<<< HEAD
    spi0: spi@b00 {
      compatible = "ralink,mt7620a-spi", "ralink,rt2880-spi";
      reg = <0xb00 0x40>;
=======
    spi@b00 {
      compatible = "ralink,mt7620a-spi", "ralink,rt5350-spi", "ralink,rt2880-spi";
      reg = <0xb00 0x100>;
>>>>>>> 4e1c826ed3... mt7620n: Add support for SPI CS1.
```

The other two files have no issues.

**Comment by rwaldron** [comment]
Here's the branch I'm cherry picking from: https://github.com/tessel/openwrt/commits/2017-04-26

**Comment by kevinmehall** [comment]
Correct.

The conflict is against [an upstream change](https://github.com/lede-project/source/commit/c550ad3d3a70b409a482896a77cfc890823d0221) that appears to be intended to have the same effect as my commit. My commit can likely be dropped, but the `Tessel.dtsi` file introduced in a subsequent commit will need to be changed to reflect the different SPI device name.

**Comment by huseyinkozan** [comment]
Hi all,

I am very sory to misguide about node versions greater than 6.5. After saw https://github.com/tessel/openwrt/pull/2 I tried to build carefully and made it success with 6.10.3. I am preparing a PR.
Hope all forgive ...

**Comment by huseyinkozan** [comment]
@rwaldron Where are we setting the version info ? 

I am getting undefined, like:
```
$ t2 version
INFO Looking for your Tessel...
INFO Connected to t.
ERR! TypeError: Cannot read property 'version' of undefined
```

**Comment by huseyinkozan** [comment]
https://huseyinkozan.com.tr/files/tmp/openwrt-ramips-mt7620-tessel-squashfs-sysupgrade-node-v6.10.3.bin
https://huseyinkozan.com.tr/files/tmp/openwrt-ramips-mt7620-tessel-squashfs-sysupgrade-node-v6.10.3.bin.sha256
